{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Mission\n",
    "\n",
    "Le projet porte sur StackOverFlow, la célèbre plateforme de questions et réponses populaire pour les développeurs.  \n",
    "La mission est de développer un système qui génère les suggestions de tags lorsqu'un utilisateur pose une question sur le site. \n",
    "Le projet se décline sous forme de 4 notebooks:  \n",
    "- un notebook avec un test du wrapper StackAPI pour récupérer 50 questions StackOverFlow     \n",
    "- un notebook d'exploration et de pré-traitement des questions récupérées   \n",
    "- un notebook avec une approche non supervisée de génération de tags     \n",
    "- un notebook avec une approche supervisée de génération de tags     "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Génération de tags - Test du wrapper StackAPI\n",
    "\n",
    "StackAPI est une bibliothèque Python qui sert de wrapper pour l'API de Stack Exchange, qui est un réseau de sites de questions-réponses. StackAPI fournit une interface simplifiée pour interagir avec l'API de Stack Exchange et permet d'effectuer des requêtes vers l'API de Stack Overflow pour accéder aux données telles que les questions, les tags, les scores... "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Installation des dépendances suivantes:  \n",
    "\n",
    "ipykernel==6.26.0  \n",
    "StackAPI==0.3.0  \n",
    "pandas==2.1.3  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from stackapi import StackAPI\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Avec la méthode fetch et le paramètres questions, on crée une requête qui nous permettra d'obtenir 50 questions, contenant le tag “python” et qui ont un score > 50 (votes)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "# On utilise les timestamps sur un an\n",
    "# Pour le 15 octobre 2020 à minuit (UTC) : 1602720000\n",
    "# Pour le 15 octobre 2023 à minuit (UTC) : 1697328000\n",
    "START_DATE=1602720000\n",
    "END_DATE=1697328000\n",
    "\n",
    "SITE = StackAPI('stackoverflow')\n",
    "SITE.page_size = 50\n",
    "SITE.max_pages = 1\n",
    "questions = SITE.fetch('questions', \n",
    "                       tagged='python', \n",
    "                       sort='votes', \n",
    "                       fromdate=START_DATE, \n",
    "                       todate=END_DATE,\n",
    "                       min=50\n",
    "                       )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'backoff': 0,\n",
       " 'has_more': True,\n",
       " 'page': 1,\n",
       " 'quota_max': 300,\n",
       " 'quota_remaining': 254,\n",
       " 'total': 0,\n",
       " 'items': [{'tags': ['python', 'pandas', 'xlrd', 'pcf'],\n",
       "   'owner': {'account_id': 20190357,\n",
       "    'reputation': 2889,\n",
       "    'user_id': 14808721,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh4.googleusercontent.com/-M5mYg2mtURw/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuck8OiIkLBi6IBucITy4XIy72uK80A/s96-c/photo.jpg?sz=256',\n",
       "    'display_name': 'Vignesh K',\n",
       "    'link': 'https://stackoverflow.com/users/14808721/vignesh-k'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 577497,\n",
       "   'closed_date': 1608122436,\n",
       "   'answer_count': 2,\n",
       "   'score': 287,\n",
       "   'last_activity_date': 1612795847,\n",
       "   'creation_date': 1607702016,\n",
       "   'last_edit_date': 1612795847,\n",
       "   'question_id': 65254535,\n",
       "   'link': 'https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported',\n",
       "   'closed_reason': 'Duplicate',\n",
       "   'title': 'xlrd.biffh.XLRDError: Excel xlsx file; not supported'},\n",
       "  {'tags': ['python', 'pandas', 'numpy', 'scikit-learn', 'python-3.7'],\n",
       "   'owner': {'account_id': 6886384,\n",
       "    'reputation': 2351,\n",
       "    'user_id': 15150567,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh6.googleusercontent.com/-OWGodLwptYQ/AAAAAAAAAAI/AAAAAAAAA1o/AMZuucmZZ7jUgnhUF3BKhul3RbeBZAF1Bw/s96-c/photo.jpg?sz=256',\n",
       "    'display_name': 'Sachit Jani',\n",
       "    'link': 'https://stackoverflow.com/users/15150567/sachit-jani'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 330082,\n",
       "   'protected_date': 1673901248,\n",
       "   'answer_count': 19,\n",
       "   'score': 225,\n",
       "   'last_activity_date': 1680884751,\n",
       "   'creation_date': 1612516308,\n",
       "   'last_edit_date': 1673850793,\n",
       "   'question_id': 66060487,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp',\n",
       "   'title': 'ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject'},\n",
       "  {'tags': ['python', 'linux', 'docker', 'docker-compose'],\n",
       "   'owner': {'account_id': 20032870,\n",
       "    'reputation': 2211,\n",
       "    'user_id': 14685247,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/0a20904979404a4f79e1d4f8bb405aab?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'ming',\n",
       "    'link': 'https://stackoverflow.com/users/14685247/ming'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 333585,\n",
       "   'answer_count': 22,\n",
       "   'score': 221,\n",
       "   'last_activity_date': 1699410067,\n",
       "   'creation_date': 1606035195,\n",
       "   'last_edit_date': 1675820908,\n",
       "   'question_id': 64952238,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version',\n",
       "   'title': 'docker.errors.DockerException: Error while fetching server API version'},\n",
       "  {'tags': ['python', 'python-3.x', 'windows-10'],\n",
       "   'owner': {'account_id': 20238494,\n",
       "    'reputation': 2013,\n",
       "    'user_id': 14842976,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh4.googleusercontent.com/-tPgUuYJN48Q/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckXs8Wy0ReqrKZ98hL19LxSjnU7mw/s96-c/photo.jpg?sz=256',\n",
       "    'display_name': 'Joseph Haywood',\n",
       "    'link': 'https://stackoverflow.com/users/14842976/joseph-haywood'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 1229666,\n",
       "   'protected_date': 1615207834,\n",
       "   'closed_date': 1691903466,\n",
       "   'accepted_answer_id': 65349178,\n",
       "   'answer_count': 25,\n",
       "   'score': 201,\n",
       "   'last_activity_date': 1695144539,\n",
       "   'creation_date': 1608242137,\n",
       "   'last_edit_date': 1661715212,\n",
       "   'question_id': 65348890,\n",
       "   'link': 'https://stackoverflow.com/questions/65348890/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store',\n",
       "   'closed_reason': 'Duplicate',\n",
       "   'title': 'Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings'},\n",
       "  {'tags': ['python', 'selenium'],\n",
       "   'owner': {'account_id': 10383148,\n",
       "    'reputation': 9210,\n",
       "    'user_id': 7657180,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/6c0ee64d62bb9980080e6881a20a15fc?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'YasserKhalil',\n",
       "    'link': 'https://stackoverflow.com/users/7657180/yasserkhalil'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 441050,\n",
       "   'protected_date': 1657217293,\n",
       "   'accepted_answer_id': 70099102,\n",
       "   'answer_count': 11,\n",
       "   'score': 198,\n",
       "   'last_activity_date': 1699941869,\n",
       "   'creation_date': 1604676159,\n",
       "   'question_id': 64717302,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/64717302/deprecationwarning-executable-path-has-been-deprecated-selenium-python',\n",
       "   'title': 'DeprecationWarning: executable_path has been deprecated selenium python'},\n",
       "  {'tags': ['python', 'macos', 'terminal', 'atom-editor', 'macos-monterey'],\n",
       "   'owner': {'account_id': 24663681,\n",
       "    'reputation': 3226,\n",
       "    'user_id': 18559642,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/13cdab4eb9d9fb5b1c7dece549f96046?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'Kirill Ignatyev',\n",
       "    'link': 'https://stackoverflow.com/users/18559642/kirill-ignatyev'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 370045,\n",
       "   'protected_date': 1673118234,\n",
       "   'accepted_answer_id': 71621142,\n",
       "   'answer_count': 18,\n",
       "   'score': 197,\n",
       "   'last_activity_date': 1675219189,\n",
       "   'creation_date': 1648058522,\n",
       "   'last_edit_date': 1656277606,\n",
       "   'question_id': 71591971,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/71591971/how-can-i-fix-the-zsh-command-not-found-python-error-macos-monterey-12-3',\n",
       "   'title': 'How can I fix the &quot;zsh: command not found: python&quot; error? (macOS Monterey 12.3, Python&amp;nbsp;3.10, Atom IDE, and atom-python-run 0.9.7)'},\n",
       "  {'tags': ['python', 'tensorflow', 'ray'],\n",
       "   'owner': {'account_id': 22989345,\n",
       "    'reputation': 1981,\n",
       "    'user_id': 17115086,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/16c137f7793988efb97ab410f7aec4f6?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'hasu33',\n",
       "    'link': 'https://stackoverflow.com/users/17115086/hasu33'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 273732,\n",
       "   'protected_date': 1689017298,\n",
       "   'answer_count': 16,\n",
       "   'score': 193,\n",
       "   'last_activity_date': 1698317855,\n",
       "   'creation_date': 1653965255,\n",
       "   'last_edit_date': 1656248470,\n",
       "   'question_id': 72441758,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly',\n",
       "   'title': 'TypeError: Descriptors cannot not be created directly'},\n",
       "  {'tags': ['python', 'pip'],\n",
       "   'owner': {'account_id': 4071073,\n",
       "    'reputation': 4567,\n",
       "    'user_id': 3344139,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 79,\n",
       "    'profile_image': 'https://i.stack.imgur.com/ytB7I.jpg?s=256&g=1',\n",
       "    'display_name': 'RunOrVeith',\n",
       "    'link': 'https://stackoverflow.com/users/3344139/runorveith'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 102219,\n",
       "   'accepted_answer_id': 65793484,\n",
       "   'answer_count': 9,\n",
       "   'score': 176,\n",
       "   'last_activity_date': 1670330583,\n",
       "   'creation_date': 1606986952,\n",
       "   'last_edit_date': 1619177945,\n",
       "   'question_id': 65122957,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/65122957/resolving-new-pip-backtracking-runtime-issue',\n",
       "   'title': 'Resolving new pip backtracking runtime issue'},\n",
       "  {'tags': ['python', 'python-black'],\n",
       "   'owner': {'account_id': 13900281,\n",
       "    'reputation': 11703,\n",
       "    'user_id': 10036039,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/8790cbc891c02fffb597317b43a063fa?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'zerocewl',\n",
       "    'link': 'https://stackoverflow.com/users/10036039/zerocewl'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 79839,\n",
       "   'accepted_answer_id': 71674345,\n",
       "   'answer_count': 6,\n",
       "   'score': 174,\n",
       "   'last_activity_date': 1679491903,\n",
       "   'creation_date': 1648626375,\n",
       "   'last_edit_date': 1651785651,\n",
       "   'question_id': 71673404,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click',\n",
       "   'title': 'ImportError: cannot import name &#39;_unicodefun&#39; from &#39;click&#39;'},\n",
       "  {'tags': ['python', 'list', 'indexing', 'swap'],\n",
       "   'owner': {'account_id': 16490432,\n",
       "    'reputation': 2730,\n",
       "    'user_id': 13860719,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://i.stack.imgur.com/9aXXj.jpg?s=256&g=1',\n",
       "    'display_name': 'Shaun Han',\n",
       "    'link': 'https://stackoverflow.com/users/13860719/shaun-han'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 22676,\n",
       "   'accepted_answer_id': 68152940,\n",
       "   'answer_count': 8,\n",
       "   'score': 172,\n",
       "   'last_activity_date': 1698106750,\n",
       "   'creation_date': 1624808189,\n",
       "   'last_edit_date': 1698106750,\n",
       "   'question_id': 68152730,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/68152730/understand-python-swapping-why-is-a-b-b-a-not-always-equivalent-to-b-a-a',\n",
       "   'title': 'Understand Python swapping: why is a, b = b, a not always equivalent to b, a = a, b?'},\n",
       "  {'tags': ['python', 'python-3.x', 'django'],\n",
       "   'owner': {'account_id': 20471934,\n",
       "    'reputation': 1867,\n",
       "    'user_id': 15022111,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh3.googleusercontent.com/a-/AOh14GglbOwwii7QET_t9MBkZTDpGTbdvrOVCOV40SkWew=k-s256',\n",
       "    'display_name': 'Hi There',\n",
       "    'link': 'https://stackoverflow.com/users/15022111/hi-there'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 82922,\n",
       "   'accepted_answer_id': 66971803,\n",
       "   'answer_count': 5,\n",
       "   'score': 171,\n",
       "   'last_activity_date': 1659887345,\n",
       "   'creation_date': 1617722621,\n",
       "   'last_edit_date': 1659887345,\n",
       "   'question_id': 66971594,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/66971594/auto-create-primary-key-used-when-not-defining-a-primary-key-type-warning-in-dja',\n",
       "   'title': 'Auto-create primary key used when not defining a primary key type warning in Django'},\n",
       "  {'tags': ['python', 'excel', 'pandas'],\n",
       "   'owner': {'account_id': 20188429,\n",
       "    'reputation': 2607,\n",
       "    'user_id': 14807216,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/b31b40bb7f63928b9dc755251aa27fc1?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'LNQ',\n",
       "    'link': 'https://stackoverflow.com/users/14807216/lnq'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 184478,\n",
       "   'protected_date': 1608777720,\n",
       "   'answer_count': 5,\n",
       "   'score': 171,\n",
       "   'last_activity_date': 1667945202,\n",
       "   'creation_date': 1607684916,\n",
       "   'last_edit_date': 1607938283,\n",
       "   'question_id': 65250207,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/65250207/pandas-cannot-open-an-excel-xlsx-file',\n",
       "   'title': 'Pandas cannot open an Excel (.xlsx) file'},\n",
       "  {'tags': ['python', 'django', 'django-urls', 'django-4.0'],\n",
       "   'owner': {'account_id': 39506,\n",
       "    'reputation': 301155,\n",
       "    'user_id': 113962,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 87,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/b80ae1d65878cf68a4b1a00848467527?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'Alasdair',\n",
       "    'link': 'https://stackoverflow.com/users/113962/alasdair'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 189594,\n",
       "   'protected_date': 1688169134,\n",
       "   'accepted_answer_id': 70319607,\n",
       "   'answer_count': 5,\n",
       "   'score': 169,\n",
       "   'last_activity_date': 1690610954,\n",
       "   'creation_date': 1639262655,\n",
       "   'question_id': 70319606,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/70319606/importerror-cannot-import-name-url-from-django-conf-urls-after-upgrading-to',\n",
       "   'title': 'ImportError: cannot import name &#39;url&#39; from &#39;django.conf.urls&#39; after upgrading to Django 4.0'},\n",
       "  {'tags': ['python', 'error-handling', 'pip'],\n",
       "   'owner': {'account_id': 23480036,\n",
       "    'reputation': 1616,\n",
       "    'user_id': 17532318,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/d37672946ecec10b2814be93daa910ef?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'Apoliticalboy',\n",
       "    'link': 'https://stackoverflow.com/users/17532318/apoliticalboy'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 222908,\n",
       "   'answer_count': 17,\n",
       "   'score': 150,\n",
       "   'last_activity_date': 1700813401,\n",
       "   'creation_date': 1677700339,\n",
       "   'last_edit_date': 1694084649,\n",
       "   'question_id': 75608323,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3',\n",
       "   'title': 'How do I solve &quot;error: externally-managed-environment&quot; every time I use pip 3?'},\n",
       "  {'tags': ['python', 'pandas', 'dataframe', 'attributeerror'],\n",
       "   'owner': {'account_id': 18651684,\n",
       "    'reputation': 1663,\n",
       "    'user_id': 13595011,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh3.googleusercontent.com/a-/AOh14Gja1Bf3zfNP7LY4HSFgp6beG2pul2AVcXIsoLC52g=k-s256',\n",
       "    'display_name': 'Maksimjeet Chowdhary',\n",
       "    'link': 'https://stackoverflow.com/users/13595011/maksimjeet-chowdhary'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 259776,\n",
       "   'protected_date': 1695993982,\n",
       "   'answer_count': 3,\n",
       "   'score': 148,\n",
       "   'last_activity_date': 1699567288,\n",
       "   'creation_date': 1680851159,\n",
       "   'last_edit_date': 1691967377,\n",
       "   'question_id': 75956209,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append',\n",
       "   'title': 'Error &quot;&#39;DataFrame&#39; object has no attribute &#39;append&#39;&quot;'},\n",
       "  {'tags': ['python', 'machine-learning', 'package', 'conda', 'python-poetry'],\n",
       "   'owner': {'account_id': 1449869,\n",
       "    'reputation': 2561,\n",
       "    'user_id': 1367124,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 68,\n",
       "    'profile_image': 'https://i.stack.imgur.com/azGrD.jpg?s=256&g=1',\n",
       "    'display_name': 'Seub',\n",
       "    'link': 'https://stackoverflow.com/users/1367124/seub'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 61121,\n",
       "   'accepted_answer_id': 71110028,\n",
       "   'answer_count': 3,\n",
       "   'score': 142,\n",
       "   'last_activity_date': 1699380700,\n",
       "   'creation_date': 1643123383,\n",
       "   'last_edit_date': 1643126235,\n",
       "   'question_id': 70851048,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/70851048/does-it-make-sense-to-use-conda-poetry',\n",
       "   'title': 'Does it make sense to use Conda + Poetry?'},\n",
       "  {'tags': ['python', 'python-3.x', 'windows', 'numpy'],\n",
       "   'owner': {'account_id': 19883764,\n",
       "    'reputation': 1403,\n",
       "    'user_id': 14567162,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh4.googleusercontent.com/-8ED7m_am4Uo/AAAAAAAAAAI/AAAAAAAAAbU/AMZuuclxX7dkrrBdmjNHqH7VsijjuTKGIg/s96-c/photo.jpg?sz=256',\n",
       "    'display_name': 'Reed Collins',\n",
       "    'link': 'https://stackoverflow.com/users/14567162/reed-collins'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 85465,\n",
       "   'protected_date': 1605219106,\n",
       "   'accepted_answer_id': 64658254,\n",
       "   'answer_count': 9,\n",
       "   'score': 140,\n",
       "   'last_activity_date': 1610096233,\n",
       "   'creation_date': 1604360224,\n",
       "   'last_edit_date': 1605519690,\n",
       "   'question_id': 64654805,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an',\n",
       "   'title': 'How do you fix &quot;runtimeError: package fails to pass a sanity check&quot; for numpy and pandas?'},\n",
       "  {'tags': ['python', 'pandas', 'dataframe', 'data-wrangling', 'data-munging'],\n",
       "   'owner': {'account_id': 29727,\n",
       "    'reputation': 4393,\n",
       "    'user_id': 80544,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 79,\n",
       "    'profile_image': 'https://i.stack.imgur.com/HtN07.jpg?s=256&g=1',\n",
       "    'display_name': 'Glenn',\n",
       "    'link': 'https://stackoverflow.com/users/80544/glenn'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 175003,\n",
       "   'accepted_answer_id': 70837545,\n",
       "   'answer_count': 8,\n",
       "   'score': 140,\n",
       "   'last_activity_date': 1690552412,\n",
       "   'creation_date': 1643042804,\n",
       "   'last_edit_date': 1645482240,\n",
       "   'question_id': 70837397,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/70837397/good-alternative-to-pandas-append-method-now-that-it-is-being-deprecated',\n",
       "   'title': 'Good alternative to Pandas .append() method, now that it is being deprecated?'},\n",
       "  {'tags': ['python', 'tensorflow', 'anaconda'],\n",
       "   'owner': {'account_id': 10181486,\n",
       "    'reputation': 3279,\n",
       "    'user_id': 7518091,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 91,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/f8af9d177a327eaf22be1651863a103a?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'user1315789',\n",
       "    'link': 'https://stackoverflow.com/users/7518091/user1315789'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 228559,\n",
       "   'accepted_answer_id': 65333085,\n",
       "   'answer_count': 8,\n",
       "   'score': 134,\n",
       "   'last_activity_date': 1700233427,\n",
       "   'creation_date': 1607990716,\n",
       "   'last_edit_date': 1700233279,\n",
       "   'question_id': 65298241,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/65298241/what-does-this-tensorflow-message-mean-any-side-effect-was-the-installation-su',\n",
       "   'title': 'What does this tensorflow message mean? Any side effect? Was the installation successful?'},\n",
       "  {'tags': ['python', 'google-analytics-api'],\n",
       "   'owner': {'account_id': 6468208,\n",
       "    'reputation': 6445,\n",
       "    'user_id': 5009293,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 76,\n",
       "    'profile_image': 'https://graph.facebook.com/995762863775266/picture?type=large',\n",
       "    'display_name': 'Doug Coats',\n",
       "    'link': 'https://stackoverflow.com/users/5009293/doug-coats'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 205042,\n",
       "   'accepted_answer_id': 73932621,\n",
       "   'answer_count': 18,\n",
       "   'score': 127,\n",
       "   'last_activity_date': 1693903144,\n",
       "   'creation_date': 1663949925,\n",
       "   'last_edit_date': 1663952437,\n",
       "   'question_id': 73830524,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check',\n",
       "   'title': 'AttributeError: module &#39;lib&#39; has no attribute &#39;X509_V_FLAG_CB_ISSUER_CHECK&#39;'},\n",
       "  {'tags': ['python',\n",
       "    'django',\n",
       "    'importerror',\n",
       "    'python-module',\n",
       "    'circular-dependency'],\n",
       "   'owner': {'account_id': 9473820,\n",
       "    'reputation': 1205,\n",
       "    'user_id': 7043835,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/4203ed009a7d8e7636fcfe3c0e03ae22?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': '3WZ',\n",
       "    'link': 'https://stackoverflow.com/users/7043835/3wz'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 379914,\n",
       "   'protected_date': 1623706069,\n",
       "   'accepted_answer_id': 64809784,\n",
       "   'answer_count': 16,\n",
       "   'score': 120,\n",
       "   'last_activity_date': 1688392928,\n",
       "   'creation_date': 1605196086,\n",
       "   'last_edit_date': 1669973149,\n",
       "   'question_id': 64807163,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/64807163/importerror-cannot-import-name-from-partially-initialized-module-m',\n",
       "   'title': 'ImportError: cannot import name &#39;...&#39; from partially initialized module &#39;...&#39; (most likely due to a circular import)'},\n",
       "  {'tags': ['python',\n",
       "    'docker',\n",
       "    'docker-compose',\n",
       "    'dependencies',\n",
       "    'importerror'],\n",
       "   'owner': {'account_id': 3369545,\n",
       "    'reputation': 3171,\n",
       "    'user_id': 2829150,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 51,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/1e9c788890b3d2a8e468ed2773864b2c?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'Arie',\n",
       "    'link': 'https://stackoverflow.com/users/2829150/arie'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 151853,\n",
       "   'protected_date': 1691442712,\n",
       "   'answer_count': 15,\n",
       "   'score': 117,\n",
       "   'last_activity_date': 1699634829,\n",
       "   'creation_date': 1652208276,\n",
       "   'last_edit_date': 1667754370,\n",
       "   'question_id': 72191560,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/72191560/importerror-cannot-import-name-soft-unicode-from-markupsafe',\n",
       "   'title': 'ImportError: cannot import name &#39;soft_unicode&#39; from &#39;markupsafe&#39;'},\n",
       "  {'tags': ['python', 'python-3.x', 'linux', 'pip'],\n",
       "   'owner': {'account_id': 22984508,\n",
       "    'reputation': 1161,\n",
       "    'user_id': 17110906,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/4d835ba2d974f7b6e2c5844a29641106?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'Christopher Coco',\n",
       "    'link': 'https://stackoverflow.com/users/17110906/christopher-coco'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 141839,\n",
       "   'answer_count': 11,\n",
       "   'score': 115,\n",
       "   'last_activity_date': 1676514324,\n",
       "   'creation_date': 1633747154,\n",
       "   'last_edit_date': 1633747387,\n",
       "   'question_id': 69503329,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/69503329/pip-is-not-working-for-python-3-10-on-ubuntu',\n",
       "   'title': 'Pip is not working for Python 3.10 on Ubuntu'},\n",
       "  {'tags': ['python', 'python-3.9'],\n",
       "   'owner': {'account_id': 4650123,\n",
       "    'reputation': 34585,\n",
       "    'user_id': 3767239,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 64,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/4d6c9d978220f4ac99f6a1237288a99c?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'a_guest',\n",
       "    'link': 'https://stackoverflow.com/users/3767239/a-guest'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 11144,\n",
       "   'answer_count': 3,\n",
       "   'score': 114,\n",
       "   'last_activity_date': 1612271090,\n",
       "   'creation_date': 1611094722,\n",
       "   'last_edit_date': 1611234002,\n",
       "   'question_id': 65800344,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/65800344/what-are-soft-keywords',\n",
       "   'title': 'What are &quot;soft keywords&quot;?'},\n",
       "  {'tags': ['python', 'pip'],\n",
       "   'owner': {'account_id': 69666,\n",
       "    'reputation': 6265,\n",
       "    'user_id': 202576,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 47,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/bdf45a8317ff3471cdcc7ba2f18c79a1?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'onknows',\n",
       "    'link': 'https://stackoverflow.com/users/202576/onknows'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 151695,\n",
       "   'protected_date': 1618889077,\n",
       "   'answer_count': 12,\n",
       "   'score': 113,\n",
       "   'last_activity_date': 1674357448,\n",
       "   'creation_date': 1611639213,\n",
       "   'last_edit_date': 1674357448,\n",
       "   'question_id': 65896334,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/65896334/upgrading-pip-fails-with-syntax-error-caused-by-sys-stderr-writeferror-exc',\n",
       "   'title': 'Upgrading pip fails with syntax error caused by sys.stderr.write(f&quot;ERROR: {exc}&quot;)'},\n",
       "  {'tags': ['python', 'numpy'],\n",
       "   'owner': {'account_id': 8369136,\n",
       "    'reputation': 3432,\n",
       "    'user_id': 6284785,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 50,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/9d2ef82797b12ebbeebbf008f9524f50?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'Anatoly',\n",
       "    'link': 'https://stackoverflow.com/users/6284785/anatoly'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 213397,\n",
       "   'answer_count': 22,\n",
       "   'score': 109,\n",
       "   'last_activity_date': 1695172833,\n",
       "   'creation_date': 1614021415,\n",
       "   'last_edit_date': 1614030641,\n",
       "   'question_id': 66322049,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/66322049/could-not-install-packages-due-to-an-oserror-winerror-2-no-such-file-or-direc',\n",
       "   'title': 'Could not install packages due to an OSError: [WinError 2] No such file or directory'},\n",
       "  {'tags': ['python',\n",
       "    'selenium',\n",
       "    'google-chrome',\n",
       "    'selenium-webdriver',\n",
       "    'selenium-chromedriver'],\n",
       "   'owner': {'account_id': 19488994,\n",
       "    'reputation': 1083,\n",
       "    'user_id': 14257612,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/c49440f3d6f3831211bcb56d9614a61e?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'Alesss',\n",
       "    'link': 'https://stackoverflow.com/users/14257612/alesss'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 251168,\n",
       "   'accepted_answer_id': 72773269,\n",
       "   'answer_count': 4,\n",
       "   'score': 108,\n",
       "   'last_activity_date': 1700498304,\n",
       "   'creation_date': 1656337711,\n",
       "   'last_edit_date': 1661689426,\n",
       "   'question_id': 72773206,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el',\n",
       "   'title': 'Selenium - Python - AttributeError: &#39;WebDriver&#39; object has no attribute &#39;find_element_by_name&#39;'},\n",
       "  {'tags': ['python', 'linux', 'openssl', 'python-poetry'],\n",
       "   'owner': {'account_id': 7489950,\n",
       "    'reputation': 4646,\n",
       "    'user_id': 5692012,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 50,\n",
       "    'profile_image': 'https://i.stack.imgur.com/a3FwR.gif?s=256&g=1',\n",
       "    'display_name': 'RobinFrcd',\n",
       "    'link': 'https://stackoverflow.com/users/5692012/robinfrcd'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 192710,\n",
       "   'accepted_answer_id': 72633324,\n",
       "   'answer_count': 14,\n",
       "   'score': 107,\n",
       "   'last_activity_date': 1699036115,\n",
       "   'creation_date': 1651782719,\n",
       "   'last_edit_date': 1675089528,\n",
       "   'question_id': 72133316,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory',\n",
       "   'title': 'libssl.so.1.1: cannot open shared object file: No such file or directory'},\n",
       "  {'tags': ['python', 'windows', 'visual-studio-2022'],\n",
       "   'owner': {'account_id': 2813476,\n",
       "    'reputation': 1813,\n",
       "    'user_id': 2419205,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 52,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/5a4b5ff5c0d06ba079e8d974dd8309b4?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'Starfleet Security',\n",
       "    'link': 'https://stackoverflow.com/users/2419205/starfleet-security'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 7126,\n",
       "   'answer_count': 9,\n",
       "   'score': 105,\n",
       "   'last_activity_date': 1668277374,\n",
       "   'creation_date': 1645204638,\n",
       "   'last_edit_date': 1648802107,\n",
       "   'question_id': 71177450,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/71177450/unable-to-restore-visual-studio-2022-window-ide-itself-after-minimizing',\n",
       "   'title': 'Unable to restore Visual Studio 2022 window (IDE itself) after minimizing'},\n",
       "  {'tags': ['python', 'algorithm', 'sorting'],\n",
       "   'owner': {'account_id': 22573228,\n",
       "    'reputation': 6401,\n",
       "    'user_id': 16759116,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://i.stack.imgur.com/n2u4t.png?s=256&g=1',\n",
       "    'display_name': 'no comment',\n",
       "    'link': 'https://stackoverflow.com/users/16759116/no-comment'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 10450,\n",
       "   'accepted_answer_id': 69438471,\n",
       "   'answer_count': 5,\n",
       "   'score': 103,\n",
       "   'last_activity_date': 1675152158,\n",
       "   'creation_date': 1633356862,\n",
       "   'last_edit_date': 1675152158,\n",
       "   'question_id': 69437526,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/69437526/what-is-this-odd-sorting-algorithm',\n",
       "   'title': 'What is this odd sorting algorithm?'},\n",
       "  {'tags': ['python',\n",
       "    'string',\n",
       "    'reference',\n",
       "    'immutability',\n",
       "    'string-concatenation'],\n",
       "   'owner': {'account_id': 6666507,\n",
       "    'reputation': 1245,\n",
       "    'user_id': 5144013,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 44,\n",
       "    'profile_image': 'https://lh3.googleusercontent.com/-gaua46VyxKQ/AAAAAAAAAAI/AAAAAAAAHxg/M-29RPq_C6E/photo.jpg?sz=256',\n",
       "    'display_name': 'Master_Roshy',\n",
       "    'link': 'https://stackoverflow.com/users/5144013/master-roshy'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 6831,\n",
       "   'protected_date': 1657262192,\n",
       "   'answer_count': 4,\n",
       "   'score': 102,\n",
       "   'last_activity_date': 1657261330,\n",
       "   'creation_date': 1654830500,\n",
       "   'last_edit_date': 1654982358,\n",
       "   'question_id': 72568719,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/72568719/if-python-strings-are-immutable-why-does-it-keep-the-same-id-if-i-use-to-app',\n",
       "   'title': 'If Python strings are immutable, why does it keep the same id if I use += to append to it?'},\n",
       "  {'tags': ['python', 'cpython', 'python-internals'],\n",
       "   'owner': {'account_id': 17476274,\n",
       "    'reputation': 24744,\n",
       "    'user_id': 12671057,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/90d2e6942c69df199a95d06e0c8e9a10?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'Kelly Bundy',\n",
       "    'link': 'https://stackoverflow.com/users/12671057/kelly-bundy'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 8220,\n",
       "   'closed_date': 1643494282,\n",
       "   'answer_count': 3,\n",
       "   'score': 101,\n",
       "   'last_activity_date': 1644084297,\n",
       "   'creation_date': 1643300597,\n",
       "   'last_edit_date': 1644083484,\n",
       "   'question_id': 70882092,\n",
       "   'link': 'https://stackoverflow.com/questions/70882092/can-we-make-1-2-true',\n",
       "   'closed_reason': 'Duplicate',\n",
       "   'title': 'Can we make 1 == 2 true?'},\n",
       "  {'tags': ['python', 'python-3.x', 'pip', 'jupyter-notebook', 'conda'],\n",
       "   'owner': {'account_id': 21527425,\n",
       "    'reputation': 2301,\n",
       "    'user_id': 15867437,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/db1346a1042b8fbda4d6ee1ddafb3ac4?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'ralphiecodes',\n",
       "    'link': 'https://stackoverflow.com/users/15867437/ralphiecodes'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 85536,\n",
       "   'closed_date': 1620432464,\n",
       "   'answer_count': 1,\n",
       "   'score': 101,\n",
       "   'last_activity_date': 1641653061,\n",
       "   'creation_date': 1620429532,\n",
       "   'last_edit_date': 1641653061,\n",
       "   'question_id': 67442661,\n",
       "   'link': 'https://stackoverflow.com/questions/67442661/warning-ignoring-invalid-distribution-ip-c-python39-lib-site-packages-how-d',\n",
       "   'closed_reason': 'Duplicate',\n",
       "   'title': 'WARNING: Ignoring invalid distribution -ip (c:\\\\python39\\\\lib\\\\site-packages) How do I fix this and what does it mean?'},\n",
       "  {'tags': ['python', 'python-3.x', 'pip', 'setuptools'],\n",
       "   'owner': {'account_id': 4733240,\n",
       "    'reputation': 1279,\n",
       "    'user_id': 3828260,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 62,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/5984d52afab65b243ba2b0c34a714390?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'vamsi',\n",
       "    'link': 'https://stackoverflow.com/users/3828260/vamsi'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 99484,\n",
       "   'accepted_answer_id': 69100830,\n",
       "   'answer_count': 6,\n",
       "   'score': 100,\n",
       "   'last_activity_date': 1669694351,\n",
       "   'creation_date': 1631092630,\n",
       "   'last_edit_date': 1666626525,\n",
       "   'question_id': 69100275,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2',\n",
       "   'title': 'Error while downloading the requirements using pip install (setup command: use_2to3 is invalid.)'},\n",
       "  {'tags': ['python', 'flask', 'pytest', 'werkzeug'],\n",
       "   'owner': {'account_id': 20745029,\n",
       "    'reputation': 1491,\n",
       "    'user_id': 15233792,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://i.stack.imgur.com/2ol6b.jpg?s=256&g=1',\n",
       "    'display_name': 'stevezkw',\n",
       "    'link': 'https://stackoverflow.com/users/15233792/stevezkw'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 58499,\n",
       "   'protected_date': 1698079880,\n",
       "   'accepted_answer_id': 77214086,\n",
       "   'answer_count': 6,\n",
       "   'score': 99,\n",
       "   'last_activity_date': 1700174126,\n",
       "   'creation_date': 1696215720,\n",
       "   'last_edit_date': 1700174126,\n",
       "   'question_id': 77213053,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr',\n",
       "   'title': 'Why did Flask start failing with &quot;ImportError: cannot import name &#39;url_quote&#39; from &#39;werkzeug.urls&#39;&quot;?'},\n",
       "  {'tags': ['python', 'performance'],\n",
       "   'owner': {'account_id': 22573228,\n",
       "    'reputation': 6401,\n",
       "    'user_id': 16759116,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://i.stack.imgur.com/n2u4t.png?s=256&g=1',\n",
       "    'display_name': 'no comment',\n",
       "    'link': 'https://stackoverflow.com/users/16759116/no-comment'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 5863,\n",
       "   'accepted_answer_id': 68938778,\n",
       "   'answer_count': 5,\n",
       "   'score': 96,\n",
       "   'last_activity_date': 1632048881,\n",
       "   'creation_date': 1629981354,\n",
       "   'last_edit_date': 1632048881,\n",
       "   'question_id': 68938628,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/68938628/why-is-any-true-for-if-cond-much-faster-than-any-cond-for',\n",
       "   'title': 'Why is any (True for ... if cond) much faster than any (cond for ...)?'},\n",
       "  {'tags': ['python', 'openai-api', 'urllib3'],\n",
       "   'owner': {'account_id': 11229285,\n",
       "    'reputation': 1043,\n",
       "    'user_id': 8237910,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh5.googleusercontent.com/-OajeBMxDGMo/AAAAAAAAAAI/AAAAAAAAAmQ/8vm8L0FQK1c/photo.jpg?sz=256',\n",
       "    'display_name': 'prismwatermelon',\n",
       "    'link': 'https://stackoverflow.com/users/8237910/prismwatermelon'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 190587,\n",
       "   'accepted_answer_id': 76187415,\n",
       "   'answer_count': 12,\n",
       "   'score': 94,\n",
       "   'last_activity_date': 1699962924,\n",
       "   'creation_date': 1683349902,\n",
       "   'last_edit_date': 1691972425,\n",
       "   'question_id': 76187256,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/76187256/importerror-urllib3-v2-0-only-supports-openssl-1-1-1-currently-the-ssl-modu',\n",
       "   'title': 'ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the &#39;ssl&#39; module is compiled with LibreSSL 2.8.3'},\n",
       "  {'tags': ['python', 'django', 'docker', 'ubuntu', 'pip'],\n",
       "   'owner': {'account_id': 20491251,\n",
       "    'reputation': 1305,\n",
       "    'user_id': 15037284,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh3.googleusercontent.com/a-/AOh14GiXJgQtzUWGpNLT_i_sN60pWyqIzgZovX88hghJsw=k-s256',\n",
       "    'display_name': 'V.D.',\n",
       "    'link': 'https://stackoverflow.com/users/15037284/v-d'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 191125,\n",
       "   'accepted_answer_id': 68673356,\n",
       "   'answer_count': 4,\n",
       "   'score': 94,\n",
       "   'last_activity_date': 1695554686,\n",
       "   'creation_date': 1628195874,\n",
       "   'last_edit_date': 1651657455,\n",
       "   'question_id': 68673221,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/68673221/warning-running-pip-as-the-root-user',\n",
       "   'title': 'WARNING: Running pip as the &#39;root&#39; user'},\n",
       "  {'tags': ['python', 'prompt', 'openai-api', 'completion', 'chatgpt-api'],\n",
       "   'owner': {'account_id': 3235065,\n",
       "    'reputation': 1722,\n",
       "    'user_id': 3018860,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 89,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/edec84abcde58e8f5d45a7e5522ff1e1?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'Unix',\n",
       "    'link': 'https://stackoverflow.com/users/3018860/unix'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 202580,\n",
       "   'closed_date': 1685124780,\n",
       "   'accepted_answer_id': 75898717,\n",
       "   'answer_count': 5,\n",
       "   'score': 93,\n",
       "   'last_activity_date': 1697273724,\n",
       "   'creation_date': 1680263884,\n",
       "   'last_edit_date': 1691966958,\n",
       "   'question_id': 75898276,\n",
       "   'link': 'https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please',\n",
       "   'closed_reason': 'Not suitable for this site',\n",
       "   'title': 'OpenAI ChatGPT (GPT-3.5) API error 429: &quot;You exceeded your current quota, please check your plan and billing details&quot;'},\n",
       "  {'tags': ['python', 'pytest', 'python-3.10'],\n",
       "   'owner': {'account_id': 6059231,\n",
       "    'reputation': 1057,\n",
       "    'user_id': 7495123,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/51d3eef77d2721209626c7032be30a4f?s=256&d=identicon&r=PG',\n",
       "    'display_name': 'chydik',\n",
       "    'link': 'https://stackoverflow.com/users/7495123/chydik'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 35685,\n",
       "   'answer_count': 3,\n",
       "   'score': 93,\n",
       "   'last_activity_date': 1673130914,\n",
       "   'creation_date': 1633966389,\n",
       "   'last_edit_date': 1652127506,\n",
       "   'question_id': 69528842,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest',\n",
       "   'title': 'An error while trying to execute tests on python 3.10 with pytest'},\n",
       "  {'tags': ['python',\n",
       "    'selenium',\n",
       "    'selenium-webdriver',\n",
       "    'webdriver',\n",
       "    'findelement'],\n",
       "   'owner': {'account_id': 20236119,\n",
       "    'reputation': 1039,\n",
       "    'user_id': 17351258,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/f6e6cfd7989bb54f0fced88780be7804?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'Alexandr',\n",
       "    'link': 'https://stackoverflow.com/users/17351258/alexandr'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 125714,\n",
       "   'protected_date': 1648478045,\n",
       "   'accepted_answer_id': 69875984,\n",
       "   'answer_count': 4,\n",
       "   'score': 92,\n",
       "   'last_activity_date': 1668366084,\n",
       "   'creation_date': 1636307629,\n",
       "   'last_edit_date': 1668366084,\n",
       "   'question_id': 69875125,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/69875125/find-element-by-commands-are-deprecated-in-selenium',\n",
       "   'title': 'find_element_by_* commands are deprecated in Selenium'},\n",
       "  {'tags': ['python', 'pip', 'setuptools', 'python-poetry', 'pyproject.toml'],\n",
       "   'owner': {'account_id': 4650123,\n",
       "    'reputation': 34585,\n",
       "    'user_id': 3767239,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 64,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/4d6c9d978220f4ac99f6a1237288a99c?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'a_guest',\n",
       "    'link': 'https://stackoverflow.com/users/3767239/a-guest'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 40811,\n",
       "   'accepted_answer_id': 69711730,\n",
       "   'answer_count': 5,\n",
       "   'score': 90,\n",
       "   'last_activity_date': 1679584930,\n",
       "   'creation_date': 1635179133,\n",
       "   'question_id': 69711606,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml',\n",
       "   'title': 'How to install a package using pip in editable mode with pyproject.toml?'},\n",
       "  {'tags': ['python', 'flask', 'visual-studio-code', 'pylance'],\n",
       "   'owner': {'account_id': 19330657,\n",
       "    'reputation': 1109,\n",
       "    'user_id': 14132348,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/b87fbc6b04f4d63176c03798a7f59165?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'SMKrizan',\n",
       "    'link': 'https://stackoverflow.com/users/14132348/smkrizan'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 230955,\n",
       "   'answer_count': 14,\n",
       "   'score': 88,\n",
       "   'last_activity_date': 1701083534,\n",
       "   'creation_date': 1626962547,\n",
       "   'last_edit_date': 1663336862,\n",
       "   'question_id': 68486207,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/68486207/import-could-not-be-resolved-could-not-be-resolved-from-source-pylance-in-vs-cod',\n",
       "   'title': 'Import could not be resolved/could not be resolved from source Pylance in VS Code using Python 3.9.2 on Windows 10'},\n",
       "  {'tags': ['python', 'c++', 'python-3.x', 'rounding', 'integer-division'],\n",
       "   'owner': {'account_id': 7923772,\n",
       "    'reputation': 7078,\n",
       "    'user_id': 5983841,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 62,\n",
       "    'profile_image': 'https://i.stack.imgur.com/GHJxG.jpg?s=256&g=1',\n",
       "    'display_name': 'Rick',\n",
       "    'link': 'https://stackoverflow.com/users/5983841/rick'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 8310,\n",
       "   'accepted_answer_id': 70735005,\n",
       "   'answer_count': 8,\n",
       "   'score': 88,\n",
       "   'last_activity_date': 1660790087,\n",
       "   'creation_date': 1642342052,\n",
       "   'last_edit_date': 1643506145,\n",
       "   'question_id': 70730831,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/70730831/whats-the-mathematical-reason-behind-python-choosing-to-round-integer-division',\n",
       "   'title': 'What&#39;s the mathematical reason behind Python choosing to round integer division toward negative infinity?'},\n",
       "  {'tags': ['python', 'numpy', 'matplotlib', 'pip', 'virtualenv'],\n",
       "   'owner': {'account_id': 4597208,\n",
       "    'reputation': 47943,\n",
       "    'user_id': 3728901,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 58,\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/8621a1f0563a46ea809098b960d7923f?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'Vy Do',\n",
       "    'link': 'https://stackoverflow.com/users/3728901/vy-do'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 101502,\n",
       "   'closed_date': 1605014879,\n",
       "   'accepted_answer_id': 64730012,\n",
       "   'answer_count': 1,\n",
       "   'score': 85,\n",
       "   'last_activity_date': 1661293259,\n",
       "   'creation_date': 1604766613,\n",
       "   'last_edit_date': 1661289594,\n",
       "   'question_id': 64729944,\n",
       "   'link': 'https://stackoverflow.com/questions/64729944/runtimeerror-the-current-numpy-installation-fails-to-pass-a-sanity-check-due-to',\n",
       "   'closed_reason': 'Duplicate',\n",
       "   'title': 'RuntimeError: The current NumPy installation fails to pass a sanity check due to a bug in the windows runtime'},\n",
       "  {'tags': ['python', 'pip'],\n",
       "   'owner': {'account_id': 22347812,\n",
       "    'reputation': 905,\n",
       "    'user_id': 16566504,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://www.gravatar.com/avatar/c799fc8874aad5b346674b6e17cde358?s=256&d=identicon&r=PG&f=y&so-version=2',\n",
       "    'display_name': 'gasper101',\n",
       "    'link': 'https://stackoverflow.com/users/16566504/gasper101'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 80606,\n",
       "   'answer_count': 2,\n",
       "   'score': 85,\n",
       "   'last_activity_date': 1655718257,\n",
       "   'creation_date': 1629630703,\n",
       "   'question_id': 68880743,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/68880743/why-do-i-get-this-when-using-pip-warning-ignoring-invalid-distribution-ip',\n",
       "   'title': 'Why do I get this when using pip WARNING: Ignoring invalid distribution -ip?'},\n",
       "  {'tags': ['python', 'python-3.x', 'pip'],\n",
       "   'owner': {'account_id': 11101230,\n",
       "    'reputation': 1017,\n",
       "    'user_id': 8149861,\n",
       "    'user_type': 'registered',\n",
       "    'accept_rate': 60,\n",
       "    'profile_image': 'https://i.stack.imgur.com/Cu1Qz.jpg?s=256&g=1',\n",
       "    'display_name': 'daquezada',\n",
       "    'link': 'https://stackoverflow.com/users/8149861/daquezada'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 54901,\n",
       "   'protected_date': 1619701644,\n",
       "   'accepted_answer_id': 67244602,\n",
       "   'answer_count': 6,\n",
       "   'score': 84,\n",
       "   'last_activity_date': 1639143920,\n",
       "   'creation_date': 1619277272,\n",
       "   'last_edit_date': 1619815980,\n",
       "   'question_id': 67244301,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/67244301/warning-value-for-scheme-data-does-not-match-when-i-try-to-update-pip-or-inst',\n",
       "   'title': '&quot;WARNING: Value for scheme.data does not match&quot; when I try to update pip or install packages'},\n",
       "  {'tags': ['python',\n",
       "    'python-3.x',\n",
       "    'virtualenv',\n",
       "    'ubuntu-20.04',\n",
       "    'python-3.10'],\n",
       "   'owner': {'account_id': 17763021,\n",
       "    'reputation': 3717,\n",
       "    'user_id': 12898581,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://i.stack.imgur.com/sqYgb.jpg?s=256&g=1',\n",
       "    'display_name': 'Dhanusha_Perera07',\n",
       "    'link': 'https://stackoverflow.com/users/12898581/dhanusha-perera07'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 76240,\n",
       "   'closed_date': 1640069790,\n",
       "   'answer_count': 1,\n",
       "   'score': 83,\n",
       "   'last_activity_date': 1640069714,\n",
       "   'creation_date': 1640069714,\n",
       "   'question_id': 70431655,\n",
       "   'link': 'https://stackoverflow.com/questions/70431655/importerror-cannot-import-name-html5lib-from-pip-vendor-usr-lib-python3',\n",
       "   'closed_reason': 'Duplicate',\n",
       "   'title': 'ImportError: cannot import name &#39;html5lib&#39; from &#39;pip._vendor&#39; (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)'},\n",
       "  {'tags': ['python', 'pip'],\n",
       "   'owner': {'account_id': 15449541,\n",
       "    'reputation': 973,\n",
       "    'user_id': 17660775,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://graph.facebook.com/2328891030722501/picture?type=large',\n",
       "    'display_name': 'Abdeldjalil Sekkal',\n",
       "    'link': 'https://stackoverflow.com/users/17660775/abdeldjalil-sekkal'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 153741,\n",
       "   'protected_date': 1676571122,\n",
       "   'answer_count': 10,\n",
       "   'score': 82,\n",
       "   'last_activity_date': 1698355404,\n",
       "   'creation_date': 1653937478,\n",
       "   'last_edit_date': 1654222298,\n",
       "   'question_id': 72439001,\n",
       "   'content_license': 'CC BY-SA 4.0',\n",
       "   'link': 'https://stackoverflow.com/questions/72439001/there-was-an-error-checking-the-latest-version-of-pip',\n",
       "   'title': 'There was an error checking the latest version of pip'},\n",
       "  {'tags': ['python', 'visual-studio-code'],\n",
       "   'owner': {'account_id': 21028726,\n",
       "    'reputation': 823,\n",
       "    'user_id': 15453571,\n",
       "    'user_type': 'registered',\n",
       "    'profile_image': 'https://lh3.googleusercontent.com/a-/AOh14GgkvNdiTmCH5yWdXFlclRDM6Pjl3qSLe_RNyA6p2g=k-s256',\n",
       "    'display_name': 'Ahmed Adel',\n",
       "    'link': 'https://stackoverflow.com/users/15453571/ahmed-adel'},\n",
       "   'is_answered': True,\n",
       "   'view_count': 172684,\n",
       "   'protected_date': 1678572045,\n",
       "   'closed_date': 1678596298,\n",
       "   'answer_count': 12,\n",
       "   'score': 80,\n",
       "   'last_activity_date': 1678570245,\n",
       "   'creation_date': 1618760733,\n",
       "   'last_edit_date': 1677343850,\n",
       "   'question_id': 67150436,\n",
       "   'link': 'https://stackoverflow.com/questions/67150436/cannot-be-loaded-because-running-scripts-is-disabled-on-this-system-for-more-in',\n",
       "   'closed_reason': 'Duplicate',\n",
       "   'title': 'cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at'}]}"
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "questions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "data = []\n",
    "for question in questions['items']:\n",
    "    data.append({\n",
    "        'Date': pd.to_datetime(question['creation_date'], unit='s'),\n",
    "        'Title': question['title'],\n",
    "        'Tags': question['tags'],\n",
    "        'Score': question['score']\n",
    "    })\n",
    "\n",
    "df = pd.DataFrame(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Date</th>\n",
       "      <th>Title</th>\n",
       "      <th>Tags</th>\n",
       "      <th>Score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2020-12-11 15:53:36</td>\n",
       "      <td>xlrd.biffh.XLRDError: Excel xlsx file; not sup...</td>\n",
       "      <td>[python, pandas, xlrd, pcf]</td>\n",
       "      <td>287</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2021-02-05 09:11:48</td>\n",
       "      <td>ValueError: numpy.ndarray size changed, may in...</td>\n",
       "      <td>[python, pandas, numpy, scikit-learn, python-3.7]</td>\n",
       "      <td>225</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2020-11-22 08:53:15</td>\n",
       "      <td>docker.errors.DockerException: Error while fet...</td>\n",
       "      <td>[python, linux, docker, docker-compose]</td>\n",
       "      <td>221</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2020-12-17 21:55:37</td>\n",
       "      <td>Python was not found; run without arguments to...</td>\n",
       "      <td>[python, python-3.x, windows-10]</td>\n",
       "      <td>201</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2020-11-06 15:22:39</td>\n",
       "      <td>DeprecationWarning: executable_path has been d...</td>\n",
       "      <td>[python, selenium]</td>\n",
       "      <td>198</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2022-03-23 18:02:02</td>\n",
       "      <td>How can I fix the &amp;quot;zsh: command not found...</td>\n",
       "      <td>[python, macos, terminal, atom-editor, macos-m...</td>\n",
       "      <td>197</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2022-05-31 02:47:35</td>\n",
       "      <td>TypeError: Descriptors cannot not be created d...</td>\n",
       "      <td>[python, tensorflow, ray]</td>\n",
       "      <td>193</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2020-12-03 09:15:52</td>\n",
       "      <td>Resolving new pip backtracking runtime issue</td>\n",
       "      <td>[python, pip]</td>\n",
       "      <td>176</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2022-03-30 07:46:15</td>\n",
       "      <td>ImportError: cannot import name &amp;#39;_unicodef...</td>\n",
       "      <td>[python, python-black]</td>\n",
       "      <td>174</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2021-06-27 15:36:29</td>\n",
       "      <td>Understand Python swapping: why is a, b = b, a...</td>\n",
       "      <td>[python, list, indexing, swap]</td>\n",
       "      <td>172</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>2021-04-06 15:23:41</td>\n",
       "      <td>Auto-create primary key used when not defining...</td>\n",
       "      <td>[python, python-3.x, django]</td>\n",
       "      <td>171</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>2020-12-11 11:08:36</td>\n",
       "      <td>Pandas cannot open an Excel (.xlsx) file</td>\n",
       "      <td>[python, excel, pandas]</td>\n",
       "      <td>171</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>2021-12-11 22:44:15</td>\n",
       "      <td>ImportError: cannot import name &amp;#39;url&amp;#39; ...</td>\n",
       "      <td>[python, django, django-urls, django-4.0]</td>\n",
       "      <td>169</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>2023-03-01 19:52:19</td>\n",
       "      <td>How do I solve &amp;quot;error: externally-managed...</td>\n",
       "      <td>[python, error-handling, pip]</td>\n",
       "      <td>150</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>2023-04-07 07:05:59</td>\n",
       "      <td>Error &amp;quot;&amp;#39;DataFrame&amp;#39; object has no ...</td>\n",
       "      <td>[python, pandas, dataframe, attributeerror]</td>\n",
       "      <td>148</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>2022-01-25 15:09:43</td>\n",
       "      <td>Does it make sense to use Conda + Poetry?</td>\n",
       "      <td>[python, machine-learning, package, conda, pyt...</td>\n",
       "      <td>142</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>2020-11-02 23:37:04</td>\n",
       "      <td>How do you fix &amp;quot;runtimeError: package fai...</td>\n",
       "      <td>[python, python-3.x, windows, numpy]</td>\n",
       "      <td>140</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>2022-01-24 16:46:44</td>\n",
       "      <td>Good alternative to Pandas .append() method, n...</td>\n",
       "      <td>[python, pandas, dataframe, data-wrangling, da...</td>\n",
       "      <td>140</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>2020-12-15 00:05:16</td>\n",
       "      <td>What does this tensorflow message mean? Any si...</td>\n",
       "      <td>[python, tensorflow, anaconda]</td>\n",
       "      <td>134</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>2022-09-23 16:18:45</td>\n",
       "      <td>AttributeError: module &amp;#39;lib&amp;#39; has no at...</td>\n",
       "      <td>[python, google-analytics-api]</td>\n",
       "      <td>127</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>2020-11-12 15:48:06</td>\n",
       "      <td>ImportError: cannot import name &amp;#39;...&amp;#39; ...</td>\n",
       "      <td>[python, django, importerror, python-module, c...</td>\n",
       "      <td>120</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>2022-05-10 18:44:36</td>\n",
       "      <td>ImportError: cannot import name &amp;#39;soft_unic...</td>\n",
       "      <td>[python, docker, docker-compose, dependencies,...</td>\n",
       "      <td>117</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>2021-10-09 02:39:14</td>\n",
       "      <td>Pip is not working for Python 3.10 on Ubuntu</td>\n",
       "      <td>[python, python-3.x, linux, pip]</td>\n",
       "      <td>115</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>2021-01-19 22:18:42</td>\n",
       "      <td>What are &amp;quot;soft keywords&amp;quot;?</td>\n",
       "      <td>[python, python-3.9]</td>\n",
       "      <td>114</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>2021-01-26 05:33:33</td>\n",
       "      <td>Upgrading pip fails with syntax error caused b...</td>\n",
       "      <td>[python, pip]</td>\n",
       "      <td>113</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>2021-02-22 19:16:55</td>\n",
       "      <td>Could not install packages due to an OSError: ...</td>\n",
       "      <td>[python, numpy]</td>\n",
       "      <td>109</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>2022-06-27 13:48:31</td>\n",
       "      <td>Selenium - Python - AttributeError: &amp;#39;WebDr...</td>\n",
       "      <td>[python, selenium, google-chrome, selenium-web...</td>\n",
       "      <td>108</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>2022-05-05 20:31:59</td>\n",
       "      <td>libssl.so.1.1: cannot open shared object file:...</td>\n",
       "      <td>[python, linux, openssl, python-poetry]</td>\n",
       "      <td>107</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>2022-02-18 17:17:18</td>\n",
       "      <td>Unable to restore Visual Studio 2022 window (I...</td>\n",
       "      <td>[python, windows, visual-studio-2022]</td>\n",
       "      <td>105</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>2021-10-04 14:14:22</td>\n",
       "      <td>What is this odd sorting algorithm?</td>\n",
       "      <td>[python, algorithm, sorting]</td>\n",
       "      <td>103</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>2022-06-10 03:08:20</td>\n",
       "      <td>If Python strings are immutable, why does it k...</td>\n",
       "      <td>[python, string, reference, immutability, stri...</td>\n",
       "      <td>102</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>2022-01-27 16:23:17</td>\n",
       "      <td>Can we make 1 == 2 true?</td>\n",
       "      <td>[python, cpython, python-internals]</td>\n",
       "      <td>101</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>2021-05-07 23:18:52</td>\n",
       "      <td>WARNING: Ignoring invalid distribution -ip (c:...</td>\n",
       "      <td>[python, python-3.x, pip, jupyter-notebook, co...</td>\n",
       "      <td>101</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>2021-09-08 09:17:10</td>\n",
       "      <td>Error while downloading the requirements using...</td>\n",
       "      <td>[python, python-3.x, pip, setuptools]</td>\n",
       "      <td>100</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>2023-10-02 03:02:00</td>\n",
       "      <td>Why did Flask start failing with &amp;quot;ImportE...</td>\n",
       "      <td>[python, flask, pytest, werkzeug]</td>\n",
       "      <td>99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>2021-08-26 12:35:54</td>\n",
       "      <td>Why is any (True for ... if cond) much faster ...</td>\n",
       "      <td>[python, performance]</td>\n",
       "      <td>96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>2023-05-06 05:11:42</td>\n",
       "      <td>ImportError: urllib3 v2.0 only supports OpenSS...</td>\n",
       "      <td>[python, openai-api, urllib3]</td>\n",
       "      <td>94</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>2021-08-05 20:37:54</td>\n",
       "      <td>WARNING: Running pip as the &amp;#39;root&amp;#39; user</td>\n",
       "      <td>[python, django, docker, ubuntu, pip]</td>\n",
       "      <td>94</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>2023-03-31 11:58:04</td>\n",
       "      <td>OpenAI ChatGPT (GPT-3.5) API error 429: &amp;quot;...</td>\n",
       "      <td>[python, prompt, openai-api, completion, chatg...</td>\n",
       "      <td>93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>2021-10-11 15:33:09</td>\n",
       "      <td>An error while trying to execute tests on pyth...</td>\n",
       "      <td>[python, pytest, python-3.10]</td>\n",
       "      <td>93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>2021-11-07 17:53:49</td>\n",
       "      <td>find_element_by_* commands are deprecated in S...</td>\n",
       "      <td>[python, selenium, selenium-webdriver, webdriv...</td>\n",
       "      <td>92</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>2021-10-25 16:25:33</td>\n",
       "      <td>How to install a package using pip in editable...</td>\n",
       "      <td>[python, pip, setuptools, python-poetry, pypro...</td>\n",
       "      <td>90</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>2021-07-22 14:02:27</td>\n",
       "      <td>Import could not be resolved/could not be reso...</td>\n",
       "      <td>[python, flask, visual-studio-code, pylance]</td>\n",
       "      <td>88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>2022-01-16 14:07:32</td>\n",
       "      <td>What&amp;#39;s the mathematical reason behind Pyth...</td>\n",
       "      <td>[python, c++, python-3.x, rounding, integer-di...</td>\n",
       "      <td>88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>2020-11-07 16:30:13</td>\n",
       "      <td>RuntimeError: The current NumPy installation f...</td>\n",
       "      <td>[python, numpy, matplotlib, pip, virtualenv]</td>\n",
       "      <td>85</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>2021-08-22 11:11:43</td>\n",
       "      <td>Why do I get this when using pip WARNING: Igno...</td>\n",
       "      <td>[python, pip]</td>\n",
       "      <td>85</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>2021-04-24 15:14:32</td>\n",
       "      <td>&amp;quot;WARNING: Value for scheme.data does not ...</td>\n",
       "      <td>[python, python-3.x, pip]</td>\n",
       "      <td>84</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>2021-12-21 06:55:14</td>\n",
       "      <td>ImportError: cannot import name &amp;#39;html5lib&amp;...</td>\n",
       "      <td>[python, python-3.x, virtualenv, ubuntu-20.04,...</td>\n",
       "      <td>83</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>2022-05-30 19:04:38</td>\n",
       "      <td>There was an error checking the latest version...</td>\n",
       "      <td>[python, pip]</td>\n",
       "      <td>82</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>2021-04-18 15:45:33</td>\n",
       "      <td>cannot be loaded because running scripts is di...</td>\n",
       "      <td>[python, visual-studio-code]</td>\n",
       "      <td>80</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                  Date                                              Title  \\\n",
       "0  2020-12-11 15:53:36  xlrd.biffh.XLRDError: Excel xlsx file; not sup...   \n",
       "1  2021-02-05 09:11:48  ValueError: numpy.ndarray size changed, may in...   \n",
       "2  2020-11-22 08:53:15  docker.errors.DockerException: Error while fet...   \n",
       "3  2020-12-17 21:55:37  Python was not found; run without arguments to...   \n",
       "4  2020-11-06 15:22:39  DeprecationWarning: executable_path has been d...   \n",
       "5  2022-03-23 18:02:02  How can I fix the &quot;zsh: command not found...   \n",
       "6  2022-05-31 02:47:35  TypeError: Descriptors cannot not be created d...   \n",
       "7  2020-12-03 09:15:52       Resolving new pip backtracking runtime issue   \n",
       "8  2022-03-30 07:46:15  ImportError: cannot import name &#39;_unicodef...   \n",
       "9  2021-06-27 15:36:29  Understand Python swapping: why is a, b = b, a...   \n",
       "10 2021-04-06 15:23:41  Auto-create primary key used when not defining...   \n",
       "11 2020-12-11 11:08:36           Pandas cannot open an Excel (.xlsx) file   \n",
       "12 2021-12-11 22:44:15  ImportError: cannot import name &#39;url&#39; ...   \n",
       "13 2023-03-01 19:52:19  How do I solve &quot;error: externally-managed...   \n",
       "14 2023-04-07 07:05:59  Error &quot;&#39;DataFrame&#39; object has no ...   \n",
       "15 2022-01-25 15:09:43          Does it make sense to use Conda + Poetry?   \n",
       "16 2020-11-02 23:37:04  How do you fix &quot;runtimeError: package fai...   \n",
       "17 2022-01-24 16:46:44  Good alternative to Pandas .append() method, n...   \n",
       "18 2020-12-15 00:05:16  What does this tensorflow message mean? Any si...   \n",
       "19 2022-09-23 16:18:45  AttributeError: module &#39;lib&#39; has no at...   \n",
       "20 2020-11-12 15:48:06  ImportError: cannot import name &#39;...&#39; ...   \n",
       "21 2022-05-10 18:44:36  ImportError: cannot import name &#39;soft_unic...   \n",
       "22 2021-10-09 02:39:14       Pip is not working for Python 3.10 on Ubuntu   \n",
       "23 2021-01-19 22:18:42                What are &quot;soft keywords&quot;?   \n",
       "24 2021-01-26 05:33:33  Upgrading pip fails with syntax error caused b...   \n",
       "25 2021-02-22 19:16:55  Could not install packages due to an OSError: ...   \n",
       "26 2022-06-27 13:48:31  Selenium - Python - AttributeError: &#39;WebDr...   \n",
       "27 2022-05-05 20:31:59  libssl.so.1.1: cannot open shared object file:...   \n",
       "28 2022-02-18 17:17:18  Unable to restore Visual Studio 2022 window (I...   \n",
       "29 2021-10-04 14:14:22                What is this odd sorting algorithm?   \n",
       "30 2022-06-10 03:08:20  If Python strings are immutable, why does it k...   \n",
       "31 2022-01-27 16:23:17                           Can we make 1 == 2 true?   \n",
       "32 2021-05-07 23:18:52  WARNING: Ignoring invalid distribution -ip (c:...   \n",
       "33 2021-09-08 09:17:10  Error while downloading the requirements using...   \n",
       "34 2023-10-02 03:02:00  Why did Flask start failing with &quot;ImportE...   \n",
       "35 2021-08-26 12:35:54  Why is any (True for ... if cond) much faster ...   \n",
       "36 2023-05-06 05:11:42  ImportError: urllib3 v2.0 only supports OpenSS...   \n",
       "37 2021-08-05 20:37:54    WARNING: Running pip as the &#39;root&#39; user   \n",
       "38 2023-03-31 11:58:04  OpenAI ChatGPT (GPT-3.5) API error 429: &quot;...   \n",
       "39 2021-10-11 15:33:09  An error while trying to execute tests on pyth...   \n",
       "40 2021-11-07 17:53:49  find_element_by_* commands are deprecated in S...   \n",
       "41 2021-10-25 16:25:33  How to install a package using pip in editable...   \n",
       "42 2021-07-22 14:02:27  Import could not be resolved/could not be reso...   \n",
       "43 2022-01-16 14:07:32  What&#39;s the mathematical reason behind Pyth...   \n",
       "44 2020-11-07 16:30:13  RuntimeError: The current NumPy installation f...   \n",
       "45 2021-08-22 11:11:43  Why do I get this when using pip WARNING: Igno...   \n",
       "46 2021-04-24 15:14:32  &quot;WARNING: Value for scheme.data does not ...   \n",
       "47 2021-12-21 06:55:14  ImportError: cannot import name &#39;html5lib&...   \n",
       "48 2022-05-30 19:04:38  There was an error checking the latest version...   \n",
       "49 2021-04-18 15:45:33  cannot be loaded because running scripts is di...   \n",
       "\n",
       "                                                 Tags  Score  \n",
       "0                         [python, pandas, xlrd, pcf]    287  \n",
       "1   [python, pandas, numpy, scikit-learn, python-3.7]    225  \n",
       "2             [python, linux, docker, docker-compose]    221  \n",
       "3                    [python, python-3.x, windows-10]    201  \n",
       "4                                  [python, selenium]    198  \n",
       "5   [python, macos, terminal, atom-editor, macos-m...    197  \n",
       "6                           [python, tensorflow, ray]    193  \n",
       "7                                       [python, pip]    176  \n",
       "8                              [python, python-black]    174  \n",
       "9                      [python, list, indexing, swap]    172  \n",
       "10                       [python, python-3.x, django]    171  \n",
       "11                            [python, excel, pandas]    171  \n",
       "12          [python, django, django-urls, django-4.0]    169  \n",
       "13                      [python, error-handling, pip]    150  \n",
       "14        [python, pandas, dataframe, attributeerror]    148  \n",
       "15  [python, machine-learning, package, conda, pyt...    142  \n",
       "16               [python, python-3.x, windows, numpy]    140  \n",
       "17  [python, pandas, dataframe, data-wrangling, da...    140  \n",
       "18                     [python, tensorflow, anaconda]    134  \n",
       "19                     [python, google-analytics-api]    127  \n",
       "20  [python, django, importerror, python-module, c...    120  \n",
       "21  [python, docker, docker-compose, dependencies,...    117  \n",
       "22                   [python, python-3.x, linux, pip]    115  \n",
       "23                               [python, python-3.9]    114  \n",
       "24                                      [python, pip]    113  \n",
       "25                                    [python, numpy]    109  \n",
       "26  [python, selenium, google-chrome, selenium-web...    108  \n",
       "27            [python, linux, openssl, python-poetry]    107  \n",
       "28              [python, windows, visual-studio-2022]    105  \n",
       "29                       [python, algorithm, sorting]    103  \n",
       "30  [python, string, reference, immutability, stri...    102  \n",
       "31                [python, cpython, python-internals]    101  \n",
       "32  [python, python-3.x, pip, jupyter-notebook, co...    101  \n",
       "33              [python, python-3.x, pip, setuptools]    100  \n",
       "34                  [python, flask, pytest, werkzeug]     99  \n",
       "35                              [python, performance]     96  \n",
       "36                      [python, openai-api, urllib3]     94  \n",
       "37              [python, django, docker, ubuntu, pip]     94  \n",
       "38  [python, prompt, openai-api, completion, chatg...     93  \n",
       "39                      [python, pytest, python-3.10]     93  \n",
       "40  [python, selenium, selenium-webdriver, webdriv...     92  \n",
       "41  [python, pip, setuptools, python-poetry, pypro...     90  \n",
       "42       [python, flask, visual-studio-code, pylance]     88  \n",
       "43  [python, c++, python-3.x, rounding, integer-di...     88  \n",
       "44       [python, numpy, matplotlib, pip, virtualenv]     85  \n",
       "45                                      [python, pip]     85  \n",
       "46                          [python, python-3.x, pip]     84  \n",
       "47  [python, python-3.x, virtualenv, ubuntu-20.04,...     83  \n",
       "48                                      [python, pip]     82  \n",
       "49                       [python, visual-studio-code]     80  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "display(df)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
